name: DevCard

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  devcard:
    name: devcard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get DevCard
        uses: dailydotdev/action-devcard@2.0.4
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
